version: "3.8"
services:
  frontend:
    container_name: redis-messenger-frontend
    image: node:20-alpine
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
