name: redis-messenger-prod
services:
  redis:
    container_name: redis-messenger-redis
    image: redis:7-alpine
    ports:
      - 6382:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      retries: 2
      start_period: 5s

  nginx:
    container_name: redis-messenger-nginx
    build:
      dockerfile: Dockerfile
      context: ./server/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - frontend

  postgres:
    container_name: redis-messenger-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3curepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: redis-messenger-api
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost
      - JWT_SECRET=messenger-jwt-secret
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:s3curepass@postgres:5432/postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5000"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

  frontend:
    container_name: redis-messenger-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://frontend"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  pgdata:
