name: redis-messenger-prod
services:
  redis:
    container_name: redis-messenger-redis
    image: redis:7-alpine
    ports:
      - 6382:6379

  nginx:
    container_name: redis-messenger-nginx
    build:
      dockerfile: Dockerfile
      context: ./server/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
      - frontend

  postgres:
    container_name: redis-messenger-postgres
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3curepass
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: redis-messenger-api
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost
      - JWT_SECRET=messenger-jwt-secret
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:s3curepass@postgres:5432/postgres
    volumes:
      - /app/node_modules
      - ./server:/app

  frontend:
    container_name: redis-messenger-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

volumes:
  pgdata:
